//created on: Apr 5, 2017
package co.edu.uniandes.picasFijas.punto1

//list any import classes here.
import java.util.Scanner;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;
//declare any global variables here

rule "Turno de la maquina, la respuesta del usuario fue 0P 1F"
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial(
			$id: intentosDisponibles, 
			$n: numerosGenerados, 
			$r: respuestasHumano,
			$ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == 1) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == 0))
	then
		Integer[] ultimoNum = (Integer[]) $n.get($n.size() - 1);
		List<Integer> un = Arrays.asList(ultimoNum);
		Integer[] intento = new Integer[$ng];
		List<Integer> similares = new ArrayList<>();
		List<Integer> it = new ArrayList<>();
		// Primer intento, toma dos primeros
		if($n.size() == 1){
			System.out.println("Al encontrar una fija, se busca verificar si las dos primeras cifras corresponden a una parte de la solucion");			
			it.add(un.get(0));
			it.add(un.get(1));
			for(Integer i : (List<Integer>)$nd){
				if(!un.contains(i) && !it.contains(i) && it.size() < 4){
					it.add(i);
				}
				else if(it.size() == 4){
					break;
				}
			}
			intento = it.toArray(new Integer[it.size()]);
		}
		// Mas intentos
		else{
			Integer[] penultNum = (Integer[])$n.get($n.size() - 2);
			Respuesta penultRes = (Respuesta)$r.get($r.size()-2);
			Integer penultPicas = penultRes.getAciertos().get(TipoRespuesta.PICAS);
			Integer ultimPicas = $ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS);
			Integer penultFijas = penultRes.getAciertos().get(TipoRespuesta.FIJAS);
			Integer ultimFijas = $ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS);
			// Valida si respuesta anterior fue igual, toma similares descarta los demas, agrega nuevo
			if(penultPicas == ultimPicas && penultFijas == ultimFijas){
				System.out.println("Los ultimos dos intentos son muy similares, por tanto se descartaran las cifras no similares");
				List<Integer> p = Arrays.asList(penultNum);
				List<Integer> u = Arrays.asList(ultimoNum);
				for(Integer i : u){
					if(!p.contains(i)){
						// eliminar cada elemento no comun
						// informar usuario
						System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
						generador.quitarNumeroLista(i);
					}
					else if(!similares.contains(i)){	// agrega los similares
						similares.add(i);
					}		
				}
				for(Integer i : p){
					if(!u.contains(i)){
						// eliminar cada elemento no comun
						// informar usuario
						System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
						generador.quitarNumeroLista(i);
					}
					else if(!similares.contains(i)){	// agrega los similares
						similares.add(i);
					}
				}
				intento = similares.toArray(new Integer[similares.size()]);
			}
			// Si la respuesta anterior fue Mayor, (2P 2F, 3P 1F) ya existen reglas de ese flujo
			
			// Si la respuesta anterior fue peor (0P 0F), ya existen reglas que gestionan ese evento
		}
		
		h.agregarNumero(intento);
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));			
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};
end

rule "Turno de la maquina, la respuesta del usuario fue 2P 1F"
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial(
			$id: intentosDisponibles, 
			$n: numerosGenerados, 
			$r: respuestasHumano,
			$ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == 1) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == 2))
	then
		Integer[] ultimoNum = (Integer[]) $n.get($n.size() - 1);
		List<Integer> un = Arrays.asList(ultimoNum);
		Integer[] intento = new Integer[$ng];
		List<Integer> similares = new ArrayList<>();
		List<Integer> it = new ArrayList<>();
		// Primer intento, toma tres primeros
		if($n.size() == 1){
			System.out.println("Al encontrar 2 picas y una fija, se busca verificar si las tres primeras cifras corresponden a una parte de la solucion");			
			it.add(un.get(0));
			it.add(un.get(1));
			it.add(un.get(2));
			for(Integer i : (List<Integer>)$nd){
				if(!un.contains(i) && !it.contains(i) && it.size() < 4){
					it.add(i);
				}
				else if(it.size() == 4){
					break;
				}
			}
			intento = it.toArray(new Integer[it.size()]);
		}
		// Mas intentos
		else{
			Integer[] penultNum = (Integer[])$n.get($n.size() - 2);
			Respuesta penultRes = (Respuesta)$r.get($r.size()-2);
			Integer penultPicas = penultRes.getAciertos().get(TipoRespuesta.PICAS);
			Integer ultimPicas = $ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS);
			Integer penultFijas = penultRes.getAciertos().get(TipoRespuesta.FIJAS);
			Integer ultimFijas = $ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS);
			// Valida si respuesta anterior fue igual, toma similares descarta los demas, agrega nuevo
			if(penultPicas == ultimPicas && penultFijas == ultimFijas){
				System.out.println("Los ultimos dos intentos son muy similares, por tanto se descartaran las cifras no similares");
				List<Integer> p = Arrays.asList(penultNum);
				List<Integer> u = Arrays.asList(ultimoNum);
				for(Integer i : u){
					if(!p.contains(i)){
						// eliminar cada elemento no comun
						// informar usuario
						System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
						generador.quitarNumeroLista(i);
					}
					else if(!similares.contains(i)){	// agrega los similares
						similares.add(i);
					}		
				}
				for(Integer i : p){
					if(!u.contains(i)){
						// eliminar cada elemento no comun
						// informar usuario
						System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
						generador.quitarNumeroLista(i);
					}
					else if(!similares.contains(i)){	// agrega los similares
						similares.add(i);
					}
				}
				intento = similares.toArray(new Integer[similares.size()]);
			}
			// Si la respuesta anterior fue Mayor, (2P 2F, 3P 1F) ya existen reglas de ese flujo
			
			// Si la respuesta anterior fue peor, toma tres primeros y agrega un numero nuevos
			else if(penultPicas < ultimPicas || penultFijas < ultimFijas){
				System.out.println("Al encontrar 2 picas y una fija en el ultimo intento, y que ha mejorado la respuesta, se busca verificar si las tres primeras cifras corresponden a una parte de la solucion");
				it.add(un.get(0));
				it.add(un.get(1));
				it.add(un.get(2));
				for(Integer i : (List<Integer>)$nd){
					if(!un.contains(i) && !it.contains(i) && it.size() < 4){
						it.add(i);
					}
					else if(it.size() == 4){
						break;
					}
				}
			intento = it.toArray(new Integer[it.size()]);
			}
		}
		
		h.agregarNumero(intento);
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));			
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};
end

rule "Turno de la maquina, la respuesta del usuario fue 2P 0F"
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial(
			$id: intentosDisponibles, 
			$n: numerosGenerados, 
			$r: respuestasHumano,
			$ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == 0) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == 2))
	then
		// Primer intento
		Integer[] ultimoNum = (Integer[]) $n.get($n.size() - 1);
		List<Integer> un = Arrays.asList(ultimoNum);
		Integer[] intento = new Integer[$ng];
		List<Integer> similares = new ArrayList<>();
		if($n.size() == 1){
			System.out.println("Al encontrar 2 picas, se busca verificar si las dos primeras cifras corresponden a las picas");
			List<Integer> it = new ArrayList<>();
			it.add(un.get(0));
			it.add(un.get(1));
			for(Integer i : (List<Integer>)$nd){
				if(!un.contains(i) && !it.contains(i) && it.size() < 4){
					it.add(i);
				}
				else if(it.size() == 4){
					break;
				}
			}
			intento = it.toArray(new Integer[it.size()]);
		}
		// Mas de un intento
		else{
			Integer[] penultNum = (Integer[])$n.get($n.size() - 2);
			Respuesta penultRes = (Respuesta)$r.get($r.size()-2);
			Integer penultFijas = penultRes.getAciertos().get(TipoRespuesta.FIJAS);
			Integer ultimFijas = $ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS);
			// Si en penultimo intento, respuesta fue la misma, obtener similares, descartar los demas
			if(penultFijas == ultimFijas){
				System.out.println("Los ultimos dos intentos son muy similares, por tanto se descartaran las cifras no similares");
				List<Integer> p = Arrays.asList(penultNum);
				List<Integer> u = Arrays.asList(ultimoNum);
				for(Integer i : u){
					if(!p.contains(i)){
						// eliminar cada elemento no comun
						// informar usuario
						System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
						generador.quitarNumeroLista(i);
					}
					else if(!similares.contains(i)){	// agrega los similares
						similares.add(i);
					}		
				}
				for(Integer i : p){
					if(!u.contains(i)){
						// eliminar cada elemento no comun
						// informar usuario
						System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
						generador.quitarNumeroLista(i);
					}
					else if(!similares.contains(i)){	// agrega los similares
						similares.add(i);
					}
				}
				intento = similares.toArray(new Integer[similares.size()]);
			}
			// Si en penultimo intento, respuesta de fijas fue mayor, descartar una cifra del penultimo intento
			else if(penultFijas > ultimFijas){
				Integer posicionFinal = penultNum[3] == 9 ? 0 : penultNum[3] + 1;
				while(true){
					if(posicionFinal != penultNum[0] && posicionFinal !=  penultNum[1] && posicionFinal != penultNum[2]){
						break;
					}
					else{
						posicionFinal = posicionFinal == 9 ? 0 : posicionFinal + 1;
					}
				}						
				intento = new Integer[]{penultNum[0], penultNum[1], penultNum[2], posicionFinal};
			}
			// Si en penultimo intento, respuesta de fijas fue menor, descartar una cifra del ultimo intento
			else if(penultFijas > ultimFijas){
				Integer posicionFinal = ultimoNum[3] == 9 ? 0 : ultimoNum[3] + 1;
				while(true){
					if(posicionFinal != ultimoNum[0] && posicionFinal !=  ultimoNum[1] && posicionFinal != ultimoNum[2]){
						break;
					}
					else{
						posicionFinal = posicionFinal == 9 ? 0 : posicionFinal + 1;
					}
				}						
				intento = new Integer[]{ultimoNum[0], ultimoNum[1], ultimoNum[2], posicionFinal};
			}
		}		
		
		h.agregarNumero(intento);
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));			
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};	
end

rule "Turno de la maquina, el usuario contesta 3P y 0F"
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial(
			$id: intentosDisponibles, 
			$n: numerosGenerados, 
			$r: respuestasHumano,
			$ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == 0) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == $ng - 1))
	then
		Integer[] ultimoNum = (Integer[]) $n.get($n.size() - 1);
		Integer[] intento = new Integer[$ng];
		List<Integer> similares = new ArrayList<>();
		List<Integer> un = Arrays.asList(ultimoNum);
		// Primer intento, tomo tres
		
		List<Integer> it = new ArrayList<>();
		if($n.size() < 2){
			System.out.println("primer turno");
			Integer posicionFinal = ultimoNum[3] == 9 ? 0 : ultimoNum[3] + 1;
			while(true){
				if(posicionFinal != ultimoNum[0] && posicionFinal !=  ultimoNum[1] && posicionFinal != ultimoNum[2]){
					break;
				}
				else{
					posicionFinal = posicionFinal == 9 ? 0 : posicionFinal + 1;
				}
			}
			intento = new Integer[]{ultimoNum[0], ultimoNum[1], ultimoNum[2], posicionFinal};		
			h.agregarNumero(intento);
			System.out.println("Se obtuvieron 3 picas, se intenta validar si los tres primerons son picas");
			System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));
			
			// turno humano
			modify(t){setTurno (TipoTurno.HUMANO)};
		}
		// Si no es primer intento
		else{
			System.out.println("despues primer turno");
			Integer[] penultNum = (Integer[]) $n.get($n.size() - 2);
			Respuesta penultRes = (Respuesta) $r.get($r.size() -2);
			Integer fijasUltimTurno = (Integer)$ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS);
			Integer fijasPenultTurno = penultRes.getAciertos().get(TipoRespuesta.FIJAS);
			Integer picasPenultimoTurno = penultRes.getAciertos().get(TipoRespuesta.PICAS);
			// Si antes habian mas fijas, tomar numero anterior para convertirlo en caso de 3P y 1F
			if(fijasPenultTurno > fijasUltimTurno){
				System.out.println("mas picas en el penultimo");
				Integer[] auxiliar = new Integer[]{penultNum[2], penultNum[0], penultNum[1], penultNum[3]};
				while(true){
					if(auxiliar[0] != 0 && h.agregarNumero(auxiliar)){
						System.out.println("Se obtuvieron 3 picas, se intenta validar si se conserva el numero de fijas del anterior turno con el siguiente intento");
						System.out.println("Intento " + $n.size() + ": " + Arrays.toString(auxiliar));
						modify(t){setTurno (TipoTurno.HUMANO)};
						break;
					}
					auxiliar = new Integer[]{auxiliar[0], auxiliar[2], auxiliar[1], auxiliar[3]};
				}				
			}
			
			// Si el numero de fijas es igual, descartar los no comunes			
			else if(fijasPenultTurno == fijasUltimTurno){
				System.out.println("igual numero de fijas entre penultimo y utlimo");
				if(picasPenultimoTurno == 0){
					System.out.println("fijas = 0");
					it.add(un.get(0));
					it.add(un.get(1));
					for(Integer i : (List<Integer>)$nd){
						if(!un.contains(i) && !it.contains(i) && it.size() < 4){
							it.add(i);
						}
						else if(it.size() == 4){
							break;
						}
					}
					intento = it.toArray(new Integer[it.size()]);
					h.agregarNumero(intento);
					System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));
					// turno humano
					modify(t){setTurno (TipoTurno.HUMANO)};
				}
				else{
					System.out.println("fijas > 0");
					if($n.size() > 6){
						System.out.println("Los ultimos dos intentos son muy similares, por tanto se descartaran las cifras no similares");					
						List<Integer> p = Arrays.asList(penultNum);
						List<Integer> u = Arrays.asList(ultimoNum);
						for(Integer i : u){
							if(!p.contains(i)){
								// eliminar cada elemento no comun
								// informar usuario
								System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
								generador.quitarNumeroLista(i);
							}
							else if(!similares.contains(i)){	// agrega los similares
								similares.add(i);
							}		
						}
						for(Integer i : p){
							if(!u.contains(i)){
								// eliminar cada elemento no comun
								// informar usuario
								System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
								generador.quitarNumeroLista(i);
							}
							else if(!similares.contains(i)){	// agrega los similares
								similares.add(i);
							}
						}
						Integer[] nuevoIntento = new Integer[similares.size()];
						nuevoIntento = similares.toArray(nuevoIntento);
						h.agregarNumero(nuevoIntento);
						System.out.println("Intento " + $n.size() + ": " + Arrays.toString(nuevoIntento));
						// turno humano
						modify(t){setTurno (TipoTurno.HUMANO)};	
					}
					else{
						System.out.println("Se combinan los ultimos dos intentos");
						Integer[] nuevoIntento = new Integer[]{penultNum[0], penultNum[1], penultNum[2] ,ultimoNum[3]};
						nuevoIntento = similares.toArray(nuevoIntento);
						h.agregarNumero(nuevoIntento);
						System.out.println("Intento " + $n.size() + ": " + Arrays.toString(nuevoIntento));
						// turno humano
						modify(t){setTurno (TipoTurno.HUMANO)};
					}
				}
			}
		}
		
end

rule "Turno de la maquina, el usuario contesta 3F y 0P"
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial(
			$id: intentosDisponibles, 
			$n: numerosGenerados, 
			$r: respuestasHumano,
			$ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == 0) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == $ng - 1))
	then
		// validar si llev mas de una jugada
		Integer[] ultimoNum = (Integer[]) $n.get($n.size() - 1);
		if($n.size() >= 2){			
			Integer[] penultNum = (Integer[]) $n.get($n.size() - 2);
			if(!Collections.disjoint(Arrays.asList(ultimoNum), Arrays.asList(penultNum) ) ){
				// El intento anterior es similar al ultimo, se descartan cifras no similares
				System.out.println("Los ultimos dos intentos son muy similares, por tanto se descartaran las cifras no similares");
				List<Integer> similares = new ArrayList<>();
				List<Integer> p = Arrays.asList(penultNum);
				List<Integer> u = Arrays.asList(ultimoNum);
				for(Integer i : u){
					if(!p.contains(i)){
						// eliminar cada elemento no comun
						// informar usuario
						System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
						generador.quitarNumeroLista(i);
					}
					else if(!similares.contains(i)){	// agrega los similares
						similares.add(i);
					}		
				}
				for(Integer i : p){
					if(!u.contains(i)){
						// eliminar cada elemento no comun
						// informar usuario
						System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
						generador.quitarNumeroLista(i);
					}
					else if(!similares.contains(i)){	// agrega los similares
						similares.add(i);
					}
				}
				// Listado de disponibles distintos a los similares
				if($nd.size() == 4){
					for(Integer j : (List<Integer>)$nd){
						if(!similares.contains(j)){
							similares.add(j);
							break;
						}
					}
					
					System.out.println("El numero del usuario es: " + Arrays.toString(similares.toArray(new Integer[similares.size()])) + " porque se descartaron todas las cifras que no son fijas");
					modify(t){setTurno (TipoTurno.FINAL)};
				}
				else{					
					for(Integer j : (List<Integer>)$nd){
						if(!similares.contains(j)){
							similares.add(j);
							break;
						}
					}
					Integer[] intento = new Integer[similares.size()];
					intento = similares.toArray(intento);
					h.agregarNumero(intento);
					System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));
					// turno humano
					modify(t){setTurno (TipoTurno.HUMANO)};
				}
			}
			else{
				//Los ultimos intentos ni se parecen
				// Solo utiliza los tres primeros
				
				Integer posicionFinal = ultimoNum[3] == 9 ? 0 : ultimoNum[3] + 1;
				while(true){
					if(posicionFinal != ultimoNum[0] && posicionFinal !=  ultimoNum[1] && posicionFinal != ultimoNum[2]){
						break;
					}
					else{
						posicionFinal = posicionFinal == 9 ? 0 : posicionFinal + 1;
					}
				}
						
				Integer[] intento = new Integer[]{ultimoNum[0], ultimoNum[1], ultimoNum[2], posicionFinal};
				h.agregarNumero(intento);
				System.out.println("Se obtuvieron 3 fijas, se intenta validar si los tres primerons son fijas");
				System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));
				
				// turno humano
				modify(t){setTurno (TipoTurno.HUMANO)};
			}
		}
		// Sino
		else{
			// Primera jugada
			// Solo utiliza los tres primeros
			Integer posicionFinal = ultimoNum[3] == 9 ? 0 : ultimoNum[3] + 1;
			while(true){
				if(posicionFinal != ultimoNum[0] && posicionFinal !=  ultimoNum[1] && posicionFinal != ultimoNum[2]){
					break;
				}
				else{
					posicionFinal = posicionFinal == 9 ? 0 : posicionFinal + 1;
				}
			}
					
			Integer[] intento = new Integer[]{ultimoNum[0], ultimoNum[1], ultimoNum[2], posicionFinal};
			h.agregarNumero(intento);
			System.out.println("Se obtuvieron 3 fijas, se intenta validar si los tres primerons son fijas");
			System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));
			
			// turno humano
			modify(t){setTurno (TipoTurno.HUMANO)};
		}
end

rule "Termina juego de forma exitosa 4F 0P"
	salience 5
	when
		t: Turno(turno == TipoTurno.FINAL)
		h: Historial($id: intentosDisponibles, $n: numerosGenerados, $r: respuestasHumano)
		eval($n.size() <= $id)
	then
		System.out.println("Juego finalizado EXITOSAMENTE");
		System.out.println("Total intentos: "+ $n.size());
end

rule "Termina juego, la maquina ya no tiene intentos disponibles"
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial($id: intentosDisponibles, $n: numerosGenerados, $r: respuestasHumano)
		eval($n.size() > $id)
	then
		System.out.println("Juego finalizado, no pude adivinar el numero en maximo " + ($n.size() - 1) + " intentos");
		modify(t){setTurno (TipoTurno.FINAL)};
end

rule "Analizar si fueron todas fijas" //PARECE QUE NO FUNCIONA
	when		
		t : Turno(turno == TipoTurno.MAQUINA)
		g : Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		h: Historial($id: intentosDisponibles, $n: numerosGenerados, $r: respuestasHumano, $ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		eval ($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == $ng)
	then
		Integer[] numero = (Integer[])$n.get($n.size() -1);
		System.out.println("El numero del usuario es: " + Arrays.toString(numero) + " porque tiene " +  $ng + " fijas");
		modify(t){setTurno (TipoTurno.FINAL)};
end

rule "Analizar cuando son 4 picas"
	when 
		t : Turno(turno == TipoTurno.MAQUINA)
		g : Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		h : Historial($id: intentosDisponibles, $n: numerosGenerados, $r: respuestasHumano, $ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		eval($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == $ng)
	then
	    //traer el ultimo numero
		Integer[] numero = (Integer[])$n.get($n.size() -1);
		Integer[] auxiliar = new Integer[$ng];
		modify(g){setNumerosDisponibles(Arrays.asList(numero))}
		
		while(true)
		{
			// aca debe rotar el numero
			auxiliar[0]=numero[1];
			auxiliar[1]=numero[2];
			auxiliar[2]=numero[3];
			auxiliar[3]=numero[0];
					   			
			if (auxiliar[0] != 0 && h.agregarNumero(auxiliar))
			{
				break;
			}
			else if(auxiliar[0] == 0){
				auxiliar[0]=numero[2];
				auxiliar[1]=numero[3];
				auxiliar[2]=numero[0];
				auxiliar[3]=numero[1];
				if (auxiliar[0] != 0 && h.agregarNumero(auxiliar)){
					break;
				}
			}
		}
		
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(auxiliar));
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};
end		

rule "Analizar cuando son 3 son picas y 1 fija"
	when 
		t : Turno(turno == TipoTurno.MAQUINA)
		g : Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		h : Historial($id: intentosDisponibles, $n: numerosGenerados, $r: respuestasHumano, $ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == $ng-1) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == 1))
	then
	//traer el ultimo numero
		Integer[] numero = (Integer[])$n.get($n.size() -1);
		Integer[] auxiliar= new Integer[$ng];
		modify(g){setNumerosDisponibles(Arrays.asList(numero))}
		
		while(true)
		{
			//aca debe rotar el numero 
			auxiliar[0]=numero[0];
			auxiliar[1]=numero[2];
			auxiliar[2]=numero[3];
			auxiliar[3]=numero[1];		
			if (auxiliar[0] != 0 && h.agregarNumero(auxiliar)){
						break;				
			}
			else{
				// Fija posicion 1
				auxiliar[0]=numero[2];
				auxiliar[1]=numero[1];
				auxiliar[2]=numero[0];
				auxiliar[3]=numero[3];
				if (auxiliar[0] != 0 && h.agregarNumero(auxiliar)){
							break;						
				}
				else{
					// fija posicion 2
					auxiliar[0]=numero[1];
					auxiliar[1]=numero[3];
					auxiliar[2]=numero[2];
					auxiliar[3]=numero[0];
					if (auxiliar[0] != 0 && h.agregarNumero(auxiliar)){
								break;
					}
					else{
						// Fija posicion 3
						auxiliar[0]=numero[3];
						auxiliar[1]=numero[0];
						auxiliar[2]=numero[1];
						auxiliar[3]=numero[2];
						if (auxiliar[0]!= 0 && h.agregarNumero(auxiliar)){
									break;
						}
					}
				}
			}		
		}
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(auxiliar));
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};
end		
////////////////////////////////////////////////////////////

rule "Analizar cuando 2 son picas y 2 son fijas"
	when 
		t : Turno(turno == TipoTurno.MAQUINA)
		g : Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		h : Historial($id: intentosDisponibles, $n: numerosGenerados, $r: respuestasHumano, $ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == $ng-2) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == $ng-2))
	then
	//traer el ultimo numero
		Integer[] numero = (Integer[])$n.get($n.size() -1);
		Integer[] auxiliar= new Integer[$ng];
		modify(g){setNumerosDisponibles(Arrays.asList(numero))}
		while(true){
			//aca debe rotar el numero 
			auxiliar[0]=numero[0];
			auxiliar[1]=numero[1];
			auxiliar[2]=numero[3];
			auxiliar[3]=numero[2];
					   
			if (auxiliar[0] != 0 && h.agregarNumero(auxiliar)){
				break;
			}
			else{
				// rota 2 primeras
				auxiliar[0]=numero[1];
				auxiliar[1]=numero[0];
				auxiliar[2]=numero[2];
				auxiliar[3]=numero[3];
				if (auxiliar[0]!= 0 && h.agregarNumero(auxiliar)){
					break;
				}
				else{
					// rota 2 ultimas
					auxiliar[0]=numero[0];
					auxiliar[1]=numero[3];
					auxiliar[2]=numero[2];
					auxiliar[3]=numero[1];					   
					if (auxiliar[0] != 0 &&h.agregarNumero(auxiliar)){
						break;
					}
				}
			}
		}
					
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(auxiliar));
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};
end	

rule "Primer intento"
	salience 4
	when
		t : Turno(turno == TipoTurno.MAQUINA)
		h: Historial($id: intentosDisponibles, $n: numerosGenerados, $r: respuestasHumano)
		eval($n.size() == 1 && $r.size() == 0)
	then
		Integer[] numero = (Integer[])$n.get($n.size() -1);
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(numero));
		modify(t){setTurno (TipoTurno.HUMANO)};
end

rule "Turno de humano, la maquina tiene intentos disponibles"
	salience 5
	when
		t: Turno(turno == TipoTurno.HUMANO)
		h: Historial($id: intentosDisponibles, $n: numerosGenerados, $r: respuestasHumano)
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval($n.size() <= $id)
	then
		// Cuantas Fijas
		Scanner scanner = new Scanner(System.in);
		System.out.print("Cantidad fijas: ");
		int fijas = new Integer(scanner.nextInt()).intValue();
		// Cuantas Picas
		System.out.print("Cantidad picas: ");
		int picas = new Integer(scanner.nextInt()).intValue();
		// Validar numeros fijas o picas sea valido
		if(((picas + fijas <= $ng && picas + fijas >= 0 && picas >= 0 && fijas >= 0)||(fijas==3 && picas==1))){		
			// Si no es primera jugada			
			if(picas == 0 && fijas == 0 && $n.size() > 1 && $nd.size() <= 6){ // pregunta si ya se descartaron los primeros cuatro numeros antes
				// pedir feedback otra vez
				System.out.println("Su respuesta no es valida, el numero de fijas y picas no pueden volver a ser cero, intente otra vez o el numero ingresado no es valido si hay 3 fijas no puede haber 1 pica");
				update(t);
			}
			else if (fijas==3 && picas==1){
				System.out.println("Su respuesta no es valida si hay e fijas la otra no puede ser picas");
		    	update(t);		
			}	
			else{
				Respuesta ultimaRespuesta = new Respuesta();
				ultimaRespuesta.agregarAciertos(TipoRespuesta.FIJAS, fijas);
				ultimaRespuesta.agregarAciertos(TipoRespuesta.PICAS, picas);
				modify(h){agregarRespuestaHumano (ultimaRespuesta)};
			    // Cambiar turno maquina
				modify(t){setTurno (TipoTurno.MAQUINA)};
			}
					
		}
		else{
			// pedir feedback otra vez
			System.out.println("Su respuesta no es valida, el numero de fijas y picas no coincide con la cantidad de digitos del numero, intente otra vez");
			update(t);
		}
end

rule "Turno de maquina, no tuvo ningun acierto 0P 0F "
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial($id: intentosDisponibles, $n: numerosGenerados, $r: respuestasHumano, $ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval ($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == 0 && $ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == 0)
	then
		// eliminar numeros		
		Integer[] numeroGenerado = (Integer[])$n.get($n.size() -1);
		System.out.println("Como no se tuvo ningun acierto, se deben descartan los siguientes numeros: " + Arrays.toString(numeroGenerado));
		for(int i = 0; i < numeroGenerado.length; i++){
			modify(generador){ quitarNumeroLista(numeroGenerado[i])}
		}
		
		// generar numero		
		Integer[] nuevoNumeroGenerado = generador.generar();
		while(true){			
			if(nuevoNumeroGenerado[0] != 0 && h.agregarNumero(nuevoNumeroGenerado)){
				break;
			}
			nuevoNumeroGenerado = generador.generar();			
		}
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(nuevoNumeroGenerado));
		
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};
end

rule "Analiza cuando 1P 1F"
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial(
			$id: intentosDisponibles, 
			$n: numerosGenerados, 
			$r: respuestasHumano,
			$ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == 1) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == 1))
	then
		Integer[] numero = (Integer[])$n.get($n.size() -1);
		Integer[] auxiliar= new Integer[$ng];
		List disponibles = new ArrayList();
		disponibles=generador.getNumerosDisponibles();
		int tamaño_array=disponibles.size();
		int ultimap = tamaño_array-1;
		int penulp  = tamaño_array-2;
		
		while(true){
		
		//aca debe rotar el numero 
		auxiliar[0]=numero[0];//lo mantiene fijo
		auxiliar[1]=numero[2];//no rota, puede ser la pica
		auxiliar[2]=generador.getNumerosDisponibles().get(penulp); //PENDIENTE ASIGNAR VALORES DEL LA LISTA DE LOS NUMEROS DISPONIBLES
		auxiliar[3]=generador.getNumerosDisponibles().get(ultimap);
  
		if (auxiliar[0] != 0 && h.agregarNumero(auxiliar)){
			break;
		}
		}
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(auxiliar));
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};
end 

rule "Analiza cuando 1P 0F" //Francy
	
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial(
			$id: intentosDisponibles, 
			$n: numerosGenerados, 
			$r: respuestasHumano,
			$ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == 1) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == 0))
	then
		Integer[] ultimoNum = (Integer[]) $n.get($n.size() - 1);
		List<Integer> un = Arrays.asList(ultimoNum);
		Integer[] intento = new Integer[$ng];
		List<Integer> similares = new ArrayList<>();
		List<Integer> it = new ArrayList<>();

		
		// Primer intento, toma dos primeros
		int p=2;
		if(p == 2){
			System.out.println("Al encontrar una pica, se busca verificar si las dos primeras cifras corresponden a una parte de la solucion al cambiar sus posiciones");			
			it.add(un.get(1));
			it.add(un.get(0));
			for(Integer i : (List<Integer>)$nd){
				if(!un.contains(i) && !it.contains(i) && it.size() < 4){
					it.add(i);
				}
				else if(it.size() == 4){
					break;
				}
			}
			intento = it.toArray(new Integer[it.size()]);
			//h.agregarNumero(intento);
		}
		h.agregarNumero(intento);
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));			
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};
end 

rule "Analiza cuando 1P 2F"
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial(
			$id: intentosDisponibles, 
			$n: numerosGenerados, 
			$r: respuestasHumano,
			$ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == 2) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == 1))
	then
		Integer[] ultimoNum = (Integer[]) $n.get($n.size() - 1);
		List<Integer> un = Arrays.asList(ultimoNum);
		Integer[] intento = new Integer[$ng];
		List<Integer> similares = new ArrayList<>();
		List<Integer> it = new ArrayList<>();
		// Primer intento, toma tres primeros
		if($n.size() == 1){
			System.out.println("Al encontrar 2 fijas y una 1pica, se busca mantienen 2 fijas y se cambian de posicion otro numero");			
			it.add(un.get(0));
			it.add(un.get(1));
			it.add(un.get(3));
			for(Integer i : (List<Integer>)$nd){
				if(!un.contains(i) && !it.contains(i) && it.size() < 4){
					it.add(i);
				}
				else if(it.size() == 4){
					break;
				}
			}
			intento = it.toArray(new Integer[it.size()]);
		}
		// Mas intentos
		else{
			Integer[] penultNum = (Integer[])$n.get($n.size() - 2);
			Respuesta penultRes = (Respuesta)$r.get($r.size()-2);
			Integer penultPicas = penultRes.getAciertos().get(TipoRespuesta.PICAS);
			Integer ultimPicas = $ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS);
			Integer penultFijas = penultRes.getAciertos().get(TipoRespuesta.FIJAS);
			Integer ultimFijas = $ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS);
			// Valida si respuesta anterior fue igual, toma similares descarta los demas, agrega nuevo
			if(penultPicas == ultimPicas && penultFijas == ultimFijas){
				System.out.println("Los ultimos dos intentos son muy similares, por tanto se descartaran las cifras no similares");
				List<Integer> p = Arrays.asList(penultNum);
				List<Integer> u = Arrays.asList(ultimoNum);
				for(Integer i : u){
					if(!p.contains(i)){
						// eliminar cada elemento no comun
						// informar usuario
						System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
						generador.quitarNumeroLista(i);
					}
					else if(!similares.contains(i)){	// agrega los similares
						similares.add(i);
					}		
				}
				for(Integer i : p){
					if(!u.contains(i)){
						// eliminar cada elemento no comun
						// informar usuario
						System.out.println("Se descarta el numero " + i + " debido a que no contribuyo a aumentar el numero de fijas");
						generador.quitarNumeroLista(i);
					}
					else if(!similares.contains(i)){	// agrega los similares
						similares.add(i);
					}
				}
				intento = similares.toArray(new Integer[similares.size()]);
			}
			// Si la respuesta anterior fue Mayor, (2P 2F, 3P 1F) ya existen reglas de ese flujo
			
			// Si la respuesta anterior fue peor, toma tres primeros y agrega un numero nuevos
			else if(penultPicas < ultimPicas || penultFijas < ultimFijas){
				System.out.println("Al encontrar 2 picas y una fija en el ultimo intento, y que ha mejorado la respuesta, se busca verificar si las tres primeras cifras corresponden a una parte de la solucion");
				it.add(un.get(0));
				it.add(un.get(1));
				it.add(un.get(2));
				for(Integer i : (List<Integer>)$nd){
					if(!un.contains(i) && !it.contains(i) && it.size() < 4){
						it.add(i);
					}
					else if(it.size() == 4){
						break;
					}
				}
			intento = it.toArray(new Integer[it.size()]);
			}
		}
		
		h.agregarNumero(intento);
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));			
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};
end

rule "Analiza cuando 0P 2F"
	when
		t: Turno(turno == TipoTurno.MAQUINA)
		h: Historial(
			$id: intentosDisponibles, 
			$n: numerosGenerados, 
			$r: respuestasHumano,
			$ultimaRespuesta: respuestasHumano.get(respuestasHumano.size() -1))
		generador: Generador($nd: numerosDisponibles, $ng: numerosAGenerar)
		eval(($ultimaRespuesta.getAciertos().get(TipoRespuesta.FIJAS) == 2) && ($ultimaRespuesta.getAciertos().get(TipoRespuesta.PICAS) == 0))
	then
		// Primer intento
		Integer[] ultimoNum = (Integer[]) $n.get($n.size() - 1);
		List<Integer> un = Arrays.asList(ultimoNum);
		Integer[] intento = new Integer[$ng];
		List<Integer> similares = new ArrayList<>();
		if($n.size() == 1){
			System.out.println("Al encontrar 2 fijas mantengo las primeras y cambio las restantesas");
			List<Integer> it = new ArrayList<>();
			it.add(un.get(0));
			it.add(un.get(1));
			for(Integer i : (List<Integer>)$nd){
				if(!un.contains(i) && !it.contains(i) && it.size() < 4){
					it.add(i);
				}
				else if(it.size() == 4){
					break;
				}
			}
			intento = it.toArray(new Integer[it.size()]);
		}
		h.agregarNumero(intento);
		System.out.println("Intento " + $n.size() + ": " + Arrays.toString(intento));			
		// turno humano
		modify(t){setTurno (TipoTurno.HUMANO)};	
end
